namespace Opaline.Core.Models;

/// <summary>Subtitle / closed-caption track from player response.</summary>
public sealed class CaptionTrack
{
    public string BaseUrl { get; init; } = string.Empty;
    public string LanguageCode { get; init; } = string.Empty;
    public string LanguageName { get; init; } = string.Empty;
    public string? Kind { get; init; }
    public bool IsTranslatable { get; init; }
    public bool IsAutoGenerated => string.Equals(Kind, "asr", StringComparison.OrdinalIgnoreCase);
    public string DisplayName => IsAutoGenerated ? $"{LanguageName} (auto)" : LanguageName;
}

public sealed class ChannelPage
{
    public Channel Channel { get; init; } = new() { Id = "", Title = "" };
    public IReadOnlyList<Video> Videos { get; init; } = Array.Empty<Video>();
    public string? ContinuationToken { get; init; }
    public bool IsSubscribed { get; set; }
}

public sealed class PlaylistPage
{
    public Playlist Playlist { get; init; } = new() { Id = "", Title = "" };
    public IReadOnlyList<Video> Videos { get; init; } = Array.Empty<Video>();
    public string? ContinuationToken { get; init; }
}
